### ISSUE TITLE
Core becomes unresponsive and reboots when combining this library with other TCP functions

### ISSUE THREAD

**Issue by mawrob** [dareid/sparkcore.thingspeak#1]
The Spark forum has information on an http buffer flush issue with the TI Wi-Fi chip used by the Spark Core.  This library exhibits the same issue since the client.flush() is not a reliable way to flush the buffer and as a result the Core becomes unstable and reboots when using your library in combination with the standard Spark.function calls that also use http. See https://community.spark.io/t/core-becomes-unresponsive-after-http-request-solved/9285/14

Unfortunately I do not have the skill to fork your library but I thought you might be interested to see that this issue could likely be fixed relatively easily using the approach mentioned in the above forum post.

Thanks for your efforts!

**Comment by dareid** [comment]
Thanks for the bug report! Will look to fix this weekend.

**Comment by dareid** [comment]
The code has been updated in 39ee01c60d55cd6e59622956f44701a171989b32. Any chance you could test the code and ensure it fixes the issue?

**Comment by mawrob** [comment]
Thanks for doing this.  I will do so early this week hopefully as the
hardware is at work.  I am having an issue at the moment though with my
Spark account and am unable to compile anything.  Even the LED blink demo
gives me the following:

[image: Inline image 1]

So I need to get this fixed with Spark first.

On Sun, Mar 8, 2015 at 4:57 AM, Daniel Reid notifications@github.com
wrote:

> The code has been updated in 39ee01c
> https://github.com/dareid/sparkcore.thingspeak/commit/39ee01c60d55cd6e59622956f44701a171989b32.
> Any chance you could test the code and ensure it fixes the issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dareid/sparkcore.thingspeak/issues/1#issuecomment-77739906
> .

## 

---

Robert S. Mawrey

**Comment by mawrob** [comment]
After some testing this morning I have noticed a definite improvement although unfortunately instability still persists and the Spark Core intermittently reboots, does not respond to Spark.variable api calls, and fails the ThingSpeak write on a regular basis.

Not sure how best to proceed?  If you are interested I am happy to provide you with the code samples and details of the hardware configuration I am working with.  It might be worth me posting the details in the Spark forum for others to look at too?

**Comment by dareid** [comment]
That is a shame. Yes, if you could share your code that would help. Posting the details on the spark forum is bound to be useful too.

**Comment by mawrob** [comment]
I posted my code here.: https://github.com/mawrob/ThingSpeak-Spark

I will write up a post for the Spark forum later.

**Comment by mawrob** [comment]
I posted on the Spark forum too: http://community.spark.io/t/control-monitor-and-log-a-spark-core-with-thingspeak/10543

**Comment by mawrob** [comment]
Hi daried - the changes you made are a significant improvement and I would publish them as is.  The stability issue has not gone away completely due to likely issues with the TI Wi-Fi chip that I am guessing the new Photon will hopefully solve.
